name: Jest Test

on:
  push:
    branches: ["master", "main", "develop", "feat/init-repo"]
  pull_request:
    branches: ["master", "main", "develop", "feat/init-repo"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ./backend

    - name: Run Jest Tests
      run: yarn test
      working-directory: ./backend
